development:
:address: smtp.gmail.com
:port: 587
:authentication: plain
:user_name: lagalaxygamereviews@gmail.com
:password: launchacademy

production:
:address: smtp.gmail.com
:port: 587
:authentication: plain
:user_name: lagalaxygamereviews@gmail.com
:password: launchacademy
